### PR TITLE
Uxd 707 upgrade cypress

### PR DESCRIPTION
**Pull request by allison-c**
### Purpose 🚀

Upgrade cypress to 6

### Notes ✏️

- `get*` should be replaced to `find*`
-  Chained command will be applied to the parent element only
-  Using `find` and `findAll` explicitly
-  If `type()` doesn't work, check if the focus has been moved away, or reset the focus to the input
- Consider replacing `cy.contains(xx).should('not.be.visible')` to `xx.should('not.contain', xx)` or `.should('not. exist')`

### Updates 📦
- [ ] MAJOR (breaking) change to _these packages_
- [ ] MINOR (backward compatible) change to _these packages_
- [ ] PATCH (bug fix) change to _these packages_

### Storybook 📕
http://storybooks.highbond-s3.com/paprika/your-branch-name

### Screenshots 📸
_optional but highly recommended_

### References 🔗
_relevant Jira ticket / GitHub issues_

### CODE REVIEW

**Comment by nahumzs** [comment]
that was fast, was just find + replace? 😮

**Comment by allison-c** [comment]
> that was fast, was just find + replace? 😮

Most of them yes, some of them did some investigation but still easy to fix 😆

**Review by nahumzs — APPROVED** [review]
did you test that the change also throws an error if they were checking to the opposite? just to check that the new introduction of commands always yields true?

**Comment by allison-c** [comment]
> did you test that the change also throws an error if they were checking to the opposite? just to check that the new introduction of commands always yields true?

Yes, `find*` will throw an error if they didn't find anything, and in our tests, we usually chain `find` with `should` or `click/type` together

**Pull request merged**
