### PR TITLE
UXD-392 Upgrade react-syntax-highlighter and storybook

### PR DESCRIPTION
**Pull request by jamiek-acl**
Upgrade react-syntax-highlighter and storybook (to resolve security vulnerability in prismjs)

### CODE REVIEW

**Review by nahumzs — DISMISSED** [review]
theres was no need to upgrade storybook?

**Comment by jamiek-acl** [comment]
> theres was no need to upgrade storybook?

It was updated here:
https://github.com/acl-services/paprika/pull/752/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R57

**Comment by mikrotron** [comment]
Whoa, the navigation got all screwy:
Screen Shot 2020-10-21 at 10 43 22 AM

**Comment by nahumzs** [comment]
is it because the delimiter has change in the new storybook version @mikrotron? thank you for catching the issue 🙏

**Comment by mikrotron** [comment]
> is it because the delimiter has change in the new storybook version @mikrotron? thank you for catching the issue 🙏

@nahumzs yeah, I pushed a quick fix.

**Review by mikrotron — APPROVED** [review]
llgtm 100

**Pull request merged**
