### PR TITLE
fix(seducer): Update seducer to fix minification issues with action.types

### PR DESCRIPTION
**Pull request by Nandez89**
### Purpose 🚀
Update seducer to fix issue solved here: https://github.com/acl-services/paprika/pull/1102

### Notes ✏️
Check [this PR](https://github.com/acl-services/paprika/pull/1102) for issue description

### Updates 📦
If you have changed a component's source code (not stories, specs, or docs), before merging your branch run `yarn changeset`. This will prompt you to:
- indicate if changes were patch/minor/major for each modified package
- enter a release message

### Storybook 📕
http://storybooks.highbond-s3.com/paprika/your-branch-name

### Screenshots 📸
_optional but highly recommended_

### References 🔗
https://aclgrc.atlassian.net/browse/GRCPRD-4980

### CODE REVIEW

**Review by jamiek-acl — DISMISSED** [review]

**Comment by Nandez89** [comment]
I'm confused, came in to merge this but the merge to master already has the change to package.json 
I guess Paprika auto-updates these on the release cycle? is this still required then?

**Comment by jamiek-acl** [comment]
Yes the versions in package.json get updated by the release: https://github.com/acl-services/paprika/wiki/Releases#ci

**Comment by allison-c** [comment]
> I'm confused, came in to merge this but the merge to master already has the change to package.json
> I guess Paprika auto-updates these on the release cycle? is this still required then?

Usually no, for example, if you mark `button` as a patch release in your PR, all the other components who has `button` in the dependency list will get a patch bump as well

You can double-check in this collapsible
image

It looks like the inline-editors you want v0.2.8 has been released on Saturday, let me know if it doesn't work, I'll fix for you 😄

**Comment by Nandez89** [comment]
> > I'm confused, came in to merge this but the merge to master already has the change to package.json
> > I guess Paprika auto-updates these on the release cycle? is this still required then?
> 
> Usually no, for example, if you mark `button` as a patch release in your PR, all the other components who has `button` in the dependency list will get a patch bump as well
> 
> You can double-check in this collapsible
> image
> 
> However, if you want to update two separated components, you have to do it manually. You can either mark 2 components at the same time when you run `yarn changeset`, then they will share the same change log message. Or you can just run `yarn changeset` twice, and tag them separately, then you can put different change log message for each
> 
> It looks like the inline-editors you want v0.2.8 has been released on Saturday, let me know if it doesn't work, I'll fix for you 😄

This is really neat, I didn't know this was so automated. TIL. Seems to have worked great! thank you both for checking into this :)

**Pull request closed without merging**
