### PR TITLE
feat(Tabs): Controlled version

### PR DESCRIPTION
**Pull request by jamiek-acl**
### Purpose 🚀
Previously the `<Tabs>` component could only be run "uncontrolled" (active tab stored in internal state).  Now it can be also run "controlled" (active tab stored in external state).  This allows the consumer to change the active tabs if they want.

Issue: https://github.com/acl-services/paprika/issues/483

### Updates 📦
- [x] MINOR (backward compatible) change to Tabs

### Storybook 📕
http://storybooks.highbond-s3.com/paprika/uxd-786--set-active-tab

Screen Shot 2021-01-27 at 3 50 12 PM

### CODE REVIEW

**Comment by nahumzs** [comment]
Normally defaultValue, defaultIndex, etc are "standards" for uncontrolled components, I think would worth adding a property name `index` and used that one when it should behave as a controlled component, similarly to value and defaultValue in the Input component.

This also adds an extra benefit you now can test to check if the user intends to use the Tabs as controlled or uncontrolled, if both defaultIndex and index have an index then you can throw an error. 

Side comment, `onClick` would not be sufficient instead of `onClickTab`?

**Comment by jamiek-acl** [comment]
I don't love `index` since it is so generic.  Umm...  `activeIndex`?

re: `onClickTab`, i just like verbose names to reduce potential confusion.

**Comment by nahumzs** [comment]
sure `activeIndex` but that will break unification with defaultIndex? maybe we should deprecate defaultIndex and call it `defaultActiveIndex`,

We can make it as an alias, and console something like `console.warn("defaultActiveIndex is preferable than defaultIndex, please try to change the prop name?")` in case the user use it?


That path would not create a breaking change and alternative is just simple to make a breaking change and rename the `defaultIndex`

**Comment by mikrotron** [comment]
> Side comment, `onClick` would not be sufficient instead of `onClickTab`?

`onClick` would have to be renamed when cloned or it could conflict with a custom `onClick` passed to the individual `Tab`.  

This rename should also resolve this issue: https://github.com/acl-services/paprika/issues/888

**Comment by jamiek-acl** [comment]
I have had a classic change of heart and gone with `index`, so we can leave `defaultIndex` alone and maintain the `xxx/defaultXxx` pattern.

**Review by nahumzs — APPROVED** [review]

**Pull request merged**
