### PR TITLE
UXD-426  New Storybook helpers 🐐

### PR DESCRIPTION
**Pull request by mikrotron**
### Purpose 🚀
Make it easier to write consistent stories for Storybook.

### Notes ✏️
- Introduced `<ExampleStory>` wrapper with `storyName`, `tagline` and `fileName` (links to GitHub source) props.
- Introduced a `<StoryHeading>` component with `level` prop (only 1-3 allowed).  
- Introduced a `storyParameters` resource in `./storybook/assets` to share parameters for different types of stories.
- Refactored ONLY `<Heading>` stories to use these new helpers.
- Also experimented and decided to continue using the `<Canvas>` storybook component with the Docs examples.

### Updates 📦
- [ ] MAJOR (breaking) change to _these packages_
- [ ] MINOR (backward compatible) change to _these packages_
- [ ] PATCH (bug fix) change to _these packages_

### Storybook 📕
http://storybooks.highbond-s3.com/paprika/your-branch-name

### Screenshots 📸
_optional but highly recommended_

### References 🔗
_relevant Jira ticket / GitHub issues_

### CODE REVIEW

**Review by oscarkwan — APPROVED** [review]
LGTM

**Comment by nahumzs** [comment]
Hello peeps, can you create a story with all the components for building stories? I keep facing difficulty each time to know which component to use and from where to import them. 🙏

**Comment by mikrotron** [comment]
> Hello peeps, can you create a story with all the components for building stories? I keep facing difficulty each time to know which component to use and from where to import them. 🙏

Ha ha, it changes every week! I would have said the `<ResizeDetector>` was a good example, but now the `<Heading>` is the most up-to-date! If we did have a "template" story with all the latest patterns and tools, it would be more work to keep it up-to-date than it would be worth 😓  

But I hear your pain, and we do need to figure out something.  I will give it some thought 🤔 

ps I think I want to try replace the `knobs` in a story with the new `controls` and then I might be pretty settled on patterns for a while 🤞 
https://storybook.js.org/docs/react/essentials/controls

**Comment by alexzherdev** [comment]
@mikrotron So `Canvas` is basically what we wanted with `CodeViewer`?

**Comment by mikrotron** [comment]
> @mikrotron So `Canvas` is basically what we wanted with `CodeViewer`?

Maybe, but I'm not so sure it will work with the `knobs`, which I think is key.  Worth trying out, maybe when I experiment with the new [controls](https://storybook.js.org/docs/react/essentials/controls) 😁

**Pull request merged**
