### PR TITLE
AD-4014 Fix popover triggering by keyboard

### PR DESCRIPTION
**Pull request by allison-c**
### 🛠 Purpose

<Popover.Trigger> cannot triggered by keyboard

### ✏️ Notes to Reviewer

---

### 🖥 Screenshots

---

### CODE REVIEW

**Comment by nahumzs** [comment]
is adding space support right?

**Comment by alexzherdev** [comment]
Btw I don’t think triggering on enter is standard for buttons?

**Comment by nahumzs** [comment]
I think it's space and enter
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role#Keyboard_interactions

**Comment by allison-c** [comment]
> is adding space support right?

Yes, I saw we use this in raw button as well

**Pull request merged**
